### ISSUE TITLE
infer_resolution not found

### ISSUE THREAD

**Issue by shandongfx** [BiogeographyLab/gridder.github.io#8]
@Tai-Rocha 
> infer_resolution() 
Error in infer_resolution() : could not find function "infer_resolution"
>  GridDER::infer_resolution() 
Error: 'infer_resolution' is not an exported object from 'namespace:GridDER'
>  gridder::infer_resolution() 
Error in loadNamespace(x) : there is no package called ‘gridder’
>

**Comment by Tai-Rocha** [comment]
The issue was related to the update of the NAMESPACE file. It was fixed.
